filters:
  allowlist:
    allowlistConfigPaths:
      - allow-list.yaml
rules:
  preset-ja-spacing: true
  preset-ja-technical-writing: true
  spellcheck-tech-word: true
  no-mix-dearu-desumasu: false
  ja-technical-writing/no-exclamation-question-mark: false
